"""product

Revision ID: 7d58c1477f0e
Revises: bf8fb387e716
Create Date: 2024-05-04 23:38:24.019341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d58c1477f0e'
down_revision: Union[str, None] = 'bf8fb387e716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.Enum('RUB', 'BYN', 'USD', 'EUR', name='currencyenum'), nullable=False),
    sa.Column('availability', sa.Enum('IN_STOCK', 'OUT_OF_STOCK', 'COMING_SOON', name='availabilityenum'), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
